%% Run_modularFGM.m
% Main driver for the Modular Genotype–Phenotype–Fitness Model (GPFM).
%
% Description:
%   Runs all simulation regimes (SSWM; CM asexual/sexual; intermediate
%   recombination; generalizations; nested FGM) and reproduces Figures 3–6.
%   Results are saved under ./results/... or ./results_demo/... depending
%   on mode, and figures are generated by makeFigure3–6.
%
% Usage:
%   Run_modularFGM                 % full run (paper-scale)
%   Run_modularFGM('demo')         % short sanity run for reviewers/CI
%
% Outputs:
%   .mat files in ./results/ or ./results_demo/ subfolders; figures via makeFigure3–6.
%
% Reference:
%   Kim, M., Ardell, S. M., & Kryazhimskiy, S. (2025).
%   "Module-Selection Balance in the Evolution of Modular Organisms."
%
% -------------------------------------------------------------------------

function Run_modularFGM(mode)
    if nargin < 1, mode = 'demo'; end              % 'full' or 'demo'
    isDemo = strcmpi(mode, 'demo');

    % Assign results root directory depending on mode
    resultsRoot = tern(isDemo, '../results_demo', '../results');

    %% Environment setup (no manual addpath needed)
    thisDir = fileparts(mfilename('fullpath'));
    addpath(genpath(fileparts(thisDir)));                    % add /main, /simulation, /analysis, /figures
    rootDisp(thisDir);

    % Demo knobs (kept lightweight but preserves logic/outputs)
    demoCfg.numIteration      = 8;                % per-angle replicates in demo
    demoCfg.preRunSteps       = 40;
    demoCfg.numTimeStamp      = 8;
    demoCfg.recombList        = [0, 0.01, 1];     % subset
    demoCfg.initialAngles     = [atan2(1,6.4), atan2(1,0.2)];
    demoCfg.mutationRateSlow  = 1e-7;
    demoCfg.mutationRateFast  = 2e-4;

    % Full knobs
    fullCfg.numIteration      = 200;
    fullCfg.preRunSteps       = 200;
    fullCfg.numTimeStamp      = 20;
    fullCfg.recombList        = [0, 2e-4, 1e-3, 1e-2, 1e-1, 1];
    fullCfg.initialAngles     = [atan2(1,6.4), atan2(1,3.2), atan2(1,1.6), atan2(1,0.8), atan2(1,0.4), atan2(1,0.2)];
    fullCfg.mutationRateSlow  = 1e-7;
    fullCfg.mutationRateFast  = 2e-4;

    C = tern(isDemo, demoCfg, fullCfg);          % choose config

    % ---------------------------------------------------------------------
    % SECTION A. Base runs (SSWM; CM asexual; CM sexual)
    % ---------------------------------------------------------------------
    fprintf('\n=== Base runs ===\n');

    % A1) SSWM
    sectionTimer('SSWM base');    
    simParams = initializeSimParams();
    resultModularSSWM = simulateModularSSWM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularSSWM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/SSWM']);
    fname  = sprintf('%s/ModularFGM_SSWM_M%.1e.mat', outDir, simParams.mutationRate);
    save(fname, 'simParams', 'resultModularSSWM', 'ave');
    analyticalTrajectories = predictModularSSWM(simParams, ave); 
    save(fname, 'analyticalTrajectories', '-append');

    % A2) CM asexual
    sectionTimer('CM asexual');
    simParams = initializeSimParams('numIteration', C.numIteration, 'mutationRate', C.mutationRateFast);
    resultModularCM = simulateModularCM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularCM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/CM_Asexual']);
    fname  = sprintf('%s/ModularFGM_CM_Asexual_M%.1e.mat', outDir, simParams.mutationRate);
    save(fname, 'simParams', 'resultModularCM', 'ave');
    analyticalTrajectories = predictModularCM(simParams); 
    save(fname, 'analyticalTrajectories', '-append');

    % A3) CM sexual (full recombination)
    sectionTimer('CM sexual (full recombination)');
    simParams = initializeSimParams('numIteration', C.numIteration, 'mutationRate', C.mutationRateFast, 'recombinationRate', 1);
    initialParameters = freezeParam(simParams);
    simParams.populationMatrices = preRunSimulation(initialParameters, simParams, C.preRunSteps, 'rngSeed', 1);
    resultModularCM = simulateModularCM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularCM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/CM_Sexual']);
    fname  = sprintf('%s/ModularFGM_CM_Sexual_M%.1e_R%.4f.mat', outDir, simParams.mutationRate, simParams.recombinationRate);
    save(fname, 'simParams', 'resultModularCM', 'ave');
    analyticalTrajectories = predictFullRecomb(simParams, ave); 
    save(fname, 'analyticalTrajectories', '-append');

    % ---------------------------------------------------------------------
    % SECTION B. Intermediate recombination spectrum
    % ---------------------------------------------------------------------
    fprintf('\n=== Intermediate recombination spectrum ===\n');
    outDir = ensureDir(thisDir, [resultsRoot '/CM_IntermediateRecomb']);
    for r = C.recombList
        sectionTimer(sprintf('CM recombination r=%.4f', r));
        simParams = initializeSimParams('numIteration', C.numIteration, ...
                                        'mutationRate', C.mutationRateFast, ...
                                        'recombinationRate', r, ...
                                        'initialAngles', C.initialAngles);
        initialParameters = freezeParam(simParams);
        simParams.populationMatrices = preRunSimulation(initialParameters, simParams, C.preRunSteps, 'rngSeed', 1);
        resultModularCM = simulateModularCM(simParams);
        ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularCM.resultTable);
        fname = sprintf('%s/ModularFGM_CM_Recomb_R%.4f_M%.1e.mat', outDir, r, simParams.mutationRate);
        save(fname, 'simParams', 'resultModularCM', 'ave');
        analyticalTrajectories = predictFullRecomb(simParams, ave); 
        save(fname, 'analyticalTrajectories', '-append');
    end

    % ---------------------------------------------------------------------
    % SECTION C. Generalization: Unequal target sizes
    % ---------------------------------------------------------------------
    fprintf('\n=== Generalization: unequal target sizes ===\n');

    % C1) SSWM
    sectionTimer('Generalization SSWM');
    simParams = initializeSimParams('geneticTargetSize', [10, 40]);
    resultModularSSWM = simulateModularSSWM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularSSWM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/Generalization/SSWM']);
    fname  = sprintf('%s/ModularFGM_SSWM_M%.1e_Target%d.mat', outDir, simParams.mutationRate, prod(simParams.geneticTargetSize));
    save(fname, 'simParams', 'resultModularSSWM', 'ave');
    analyticalTrajectories = predictModularSSWM(simParams, ave); 
    save(fname, 'analyticalTrajectories', '-append');

    % C2) CM asexual
    sectionTimer('Generalization CM asexual');
    simParams = initializeSimParams('numIteration', C.numIteration, 'mutationRate', C.mutationRateFast, 'geneticTargetSize', [10, 40]);
    resultModularCM = simulateModularCM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularCM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/Generalization/CM_Asexual']);
    fname  = sprintf('%s/ModularFGM_CM_Asexual_M%.1e_Target%d.mat', outDir, simParams.mutationRate, prod(simParams.geneticTargetSize));
    save(fname, 'simParams', 'resultModularCM', 'ave');
    analyticalTrajectories = predictModularCM(simParams); 
    save(fname, 'analyticalTrajectories', '-append');

    % C3) CM sexual
    sectionTimer('Generalization CM sexual');
    simParams = initializeSimParams('numIteration', C.numIteration, 'mutationRate', C.mutationRateFast, 'recombinationRate', 1, 'geneticTargetSize', [10, 40]);
    initialParameters = freezeParam(simParams);
    simParams.populationMatrices = preRunSimulation(initialParameters, simParams, C.preRunSteps, 'rngSeed', 1);
    resultModularCM = simulateModularCM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultModularCM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/Generalization/CM_Sexual']);
    fname  = sprintf('%s/ModularFGM_CM_Sexual_M%.1e_R%.4f_Target%d.mat', outDir, simParams.mutationRate, simParams.recombinationRate, prod(simParams.geneticTargetSize));
    save(fname, 'simParams', 'resultModularCM', 'ave');
    analyticalTrajectories = predictFullRecomb(simParams, ave); 
    save(fname, 'analyticalTrajectories', '-append');

    % ---------------------------------------------------------------------
    % SECTION D. Nested FGM
    % ---------------------------------------------------------------------
    fprintf('\n=== Nested FGM ===\n');

    % D1) SSWM
    sectionTimer('NestedFGM SSWM');
    simParams = initializeSimParams(); simParams.moduleDimension = [10, 10];
    resultNestedSSWM = simulateNestedSSWM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultNestedSSWM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/Generalization/nestedFGM/SSWM']);
    fname  = sprintf('%s/NestedFGM_SSWM_M%.1e.mat', outDir, simParams.mutationRate);
    save(fname, 'simParams', 'resultNestedSSWM', 'ave');

    % D2) CM asexual
    sectionTimer('NestedFGM CM asexual');
    simParams = initializeSimParams('numIteration', C.numIteration, 'mutationRate', C.mutationRateFast);
    simParams.moduleDimension = [10, 10];
    resultNestedCM = simulateNestedCM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultNestedCM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/Generalization/nestedFGM/CM_Asexual']);
    fname  = sprintf('%s/NestedFGM_CM_Asexual_M%.1e.mat', outDir, simParams.mutationRate);
    save(fname, 'simParams', 'resultNestedCM', 'ave');

    % D3) CM sexual
    sectionTimer('NestedFGM CM sexual');
    simParams = initializeSimParams('numIteration', C.numIteration, 'mutationRate', C.mutationRateFast, 'recombinationRate', 1);
    simParams.moduleDimension = [10, 10];
    initialParameters = freezeParam(simParams);
    simParams.populationMatrices = preRunSimulation(initialParameters, simParams, C.preRunSteps, 'rngSeed', 1);
    resultNestedCM = simulateNestedCM(simParams);
    ave = computeAverageTrajectory(C.numTimeStamp, simParams, resultNestedCM.resultTable);
    outDir = ensureDir(thisDir, [resultsRoot '/Generalization/nestedFGM/CM_Sexual']);
    fname  = sprintf('%s/NestedFGM_CM_Sexual_M%.1e_R%.4f.mat', outDir, simParams.mutationRate, simParams.recombinationRate);
    save(fname, 'simParams', 'resultNestedCM', 'ave');

    % ---------------------------------------------------------------------
    % SECTION E. Figures 3–6
    % ---------------------------------------------------------------------
    fprintf('\n=== Reproducing figures ===\n');
    makeFigure3('ModularFGM', C.mutationRateSlow, C.mutationRateFast);
    makeFigure4(C.mutationRateFast);
    makeFigure5('ModularFGM', C.mutationRateSlow, C.mutationRateFast);
    makeFigure6('NestedFGM',  C.mutationRateSlow, C.mutationRateFast);

    fprintf('\nAll done. Mode: %s\n', mode);
end

% ============================== Helpers ==================================

function out = ensureDir(here, rel)
    out = fullfile(here, rel);
    if ~exist(out, 'dir'), mkdir(out); end
end

function sectionTimer(label)
    persistent lastT
    if isempty(lastT), lastT = tic; fprintf('\n'); return; end 
    dt = toc(lastT);
    fprintf('[%s] finished in %.2f s\n', label, dt);
    lastT = tic;
end

function rootDisp(here)
    fprintf('Added paths under: %s\n', here);
end

function y = tern(cond, a, b)
    if cond, y = a; else, y = b; end
end